# Generated by Django 4.0.4 on 2023-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=155, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='عنوان')),
                ('title_de', models.CharField(max_length=155, null=True, verbose_name='عنوان')),
                ('href', models.CharField(max_length=255, verbose_name='پیوند')),
                ('date', models.CharField(default='جمعه, 01 دی 1402 12:42:16', max_length=255, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='articlestitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='عنوان')),
                ('tid', models.CharField(max_length=255, verbose_name='شناسه شخصی ( id )')),
            ],
            options={
                'verbose_name_plural': 'عنوان این قسمت',
            },
        ),
    ]
