# Generated by Django 4.0.4 on 2024-04-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, help_text='jpg, size: 320*240', null=True, upload_to='certificates/', verbose_name='تصویر')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('loc', models.CharField(max_length=155, verbose_name='موقعیت مکانی')),
                ('loc_fa', models.CharField(max_length=155, null=True, verbose_name='موقعیت مکانی')),
                ('loc_en', models.CharField(max_length=155, null=True, verbose_name='موقعیت مکانی')),
                ('loc_de', models.CharField(max_length=155, null=True, verbose_name='موقعیت مکانی')),
                ('date', models.CharField(max_length=55, verbose_name='تاریخ')),
                ('date_fa', models.CharField(max_length=55, null=True, verbose_name='تاریخ')),
                ('date_en', models.CharField(max_length=55, null=True, verbose_name='تاریخ')),
                ('date_de', models.CharField(max_length=55, null=True, verbose_name='تاریخ')),
                ('pdate', models.CharField(default='شنبه, 18 فروردین 1403 05:36:31', max_length=255, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name_plural': 'گواهینامه ها',
            },
        ),
        migrations.CreateModel(
            name='certificatestitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='عنوان')),
                ('tid', models.CharField(max_length=255, verbose_name='شناسه شخصی ( id )')),
            ],
            options={
                'verbose_name_plural': 'عنوان این قسمت',
            },
        ),
    ]
