# Generated by Django 4.0.4 on 2023-12-22 09:12

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='غنوان')),
                ('title_fa', models.CharField(max_length=155, null=True, verbose_name='غنوان')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='غنوان')),
                ('title_de', models.CharField(max_length=155, null=True, verbose_name='غنوان')),
                ('href', models.CharField(max_length=255, verbose_name='پیوند')),
            ],
            options={
                'verbose_name_plural': 'منو',
            },
        ),
        migrations.CreateModel(
            name='SiteDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='sitedetails/', verbose_name='لوگو')),
                ('main_color', colorfield.fields.ColorField(blank=True, default='#687eff', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ اصلی')),
                ('second_color', colorfield.fields.ColorField(blank=True, default='#98e4ff', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ مکمل')),
                ('third_color', colorfield.fields.ColorField(blank=True, default='#292929', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ سوم')),
                ('header_inner_title', colorfield.fields.ColorField(blank=True, default='#292929', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ عناوین هدر')),
                ('meta_copyright', models.CharField(blank=True, help_text='owner name, domain address(example.com)', max_length=255, null=True, verbose_name='متا کپی رایت')),
                ('meta_copyright_fa', models.CharField(blank=True, help_text='owner name, domain address(example.com)', max_length=255, null=True, verbose_name='متا کپی رایت')),
                ('meta_copyright_en', models.CharField(blank=True, help_text='owner name, domain address(example.com)', max_length=255, null=True, verbose_name='متا کپی رایت')),
                ('meta_copyright_de', models.CharField(blank=True, help_text='owner name, domain address(example.com)', max_length=255, null=True, verbose_name='متا کپی رایت')),
                ('theme_color', colorfield.fields.ColorField(blank=True, default='#687eff', image_field=None, max_length=18, null=True, samples=None, verbose_name='رنگ آدرس بار مرورگر')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='کپی رایت فوتر')),
                ('copyright_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='کپی رایت فوتر')),
                ('copyright_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='کپی رایت فوتر')),
                ('copyright_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='کپی رایت فوتر')),
                ('site_title', models.CharField(max_length=255, verbose_name='عنوان سایت')),
                ('site_title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان سایت')),
                ('site_title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان سایت')),
                ('site_title_de', models.CharField(max_length=255, null=True, verbose_name='عنوان سایت')),
                ('description', models.TextField(max_length=500, verbose_name='توضیحات سایت')),
                ('description_fa', models.TextField(max_length=500, null=True, verbose_name='توضیحات سایت')),
                ('description_en', models.TextField(max_length=500, null=True, verbose_name='توضیحات سایت')),
                ('description_de', models.TextField(max_length=500, null=True, verbose_name='توضیحات سایت')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='sitedetails/', verbose_name='عکس به هنگام اشتراک گذاری')),
                ('og_description', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات به هنگام اشتراک گذاری')),
                ('og_description_fa', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات به هنگام اشتراک گذاری')),
                ('og_description_en', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات به هنگام اشتراک گذاری')),
                ('og_description_de', models.TextField(blank=True, max_length=500, null=True, verbose_name='توضیحات به هنگام اشتراک گذاری')),
                ('og_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان به هنگام اشتراک گذاری')),
                ('og_title_fa', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان به هنگام اشتراک گذاری')),
                ('og_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان به هنگام اشتراک گذاری')),
                ('og_title_de', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان به هنگام اشتراک گذاری')),
                ('site_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس سایت')),
                ('fav_icon', models.ImageField(blank=True, help_text='آیکونی که آدرس بار مرورگر کنار عنوان سایت نمایش داده میشود - size: 180*180.png', null=True, upload_to='sitedetails/', verbose_name='fav icon')),
                ('fav_icon2', models.ImageField(blank=True, help_text='size: 32*32.png', null=True, upload_to='sitedetails/', verbose_name='fav icon')),
                ('fav_icon3', models.ImageField(blank=True, help_text='size: 16*16.png', null=True, upload_to='sitedetails/', verbose_name='fav icon')),
                ('fa', models.BooleanField(default=True, verbose_name='آیا زبان فارسی نمایش داده شود؟')),
                ('de', models.BooleanField(default=True, verbose_name='آیا زبان آلمانی نمایش داده شود؟')),
                ('en', models.BooleanField(default=True, verbose_name='آیا زبان اینگیلیسی نمایش داده شود؟')),
            ],
            options={
                'verbose_name_plural': 'تنظیمات',
            },
        ),
    ]
