# Generated by Django 4.0.4 on 2024-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('Phone', models.CharField(max_length=20, verbose_name='شماره تلفن همراه')),
                ('Text', models.CharField(max_length=2000, verbose_name='متن گزارش')),
                ('File', models.FileField(blank=True, null=True, upload_to='UserReports/', verbose_name='فایل ضمیمه')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ارسال')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس',
            },
        ),
    ]
