# Generated by Django 4.0.4 on 2024-04-06 02:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='png, size: 320*530', upload_to='personal/', verbose_name='تصویر شخصی')),
                ('name', models.CharField(help_text='ترجیحا نام و نام خانوادگی', max_length=255, verbose_name='عنوان توضیحات')),
                ('name_fa', models.CharField(help_text='ترجیحا نام و نام خانوادگی', max_length=255, null=True, verbose_name='عنوان توضیحات')),
                ('name_en', models.CharField(help_text='ترجیحا نام و نام خانوادگی', max_length=255, null=True, verbose_name='عنوان توضیحات')),
                ('name_de', models.CharField(help_text='ترجیحا نام و نام خانوادگی', max_length=255, null=True, verbose_name='عنوان توضیحات')),
                ('position', models.CharField(blank=True, max_length=355, null=True, verbose_name='سمت, موقعیت کاری')),
                ('position_fa', models.CharField(blank=True, max_length=355, null=True, verbose_name='سمت, موقعیت کاری')),
                ('position_en', models.CharField(blank=True, max_length=355, null=True, verbose_name='سمت, موقعیت کاری')),
                ('position_de', models.CharField(blank=True, max_length=355, null=True, verbose_name='سمت, موقعیت کاری')),
                ('desc', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('desc_fa', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('desc_en', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('desc_de', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('date', models.CharField(default='شنبه, 18 فروردین 1403 05:36:31', max_length=255, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name_plural': 'توضیحات شخصی',
            },
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='عنوان', max_length=255, verbose_name='عنوان توضیحات')),
                ('name_fa', models.CharField(help_text='عنوان', max_length=255, null=True, verbose_name='عنوان توضیحات')),
                ('name_en', models.CharField(help_text='عنوان', max_length=255, null=True, verbose_name='عنوان توضیحات')),
                ('name_de', models.CharField(help_text='عنوان', max_length=255, null=True, verbose_name='عنوان توضیحات')),
                ('img', models.ImageField(help_text='png, size: 512*512 - The color not important because the program itself does it', upload_to='Social/', verbose_name='تصویر')),
                ('href', models.CharField(max_length=255, verbose_name='پیوند')),
                ('date', models.CharField(default='شنبه, 18 فروردین 1403 05:36:31', max_length=255, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('desc_fa', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('desc_en', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('desc_de', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('date', models.CharField(default='شنبه, 18 فروردین 1403 05:36:31', max_length=255, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name_plural': 'وضعیت ها',
            },
        ),
    ]
