# Generated by Django 4.0.4 on 2023-12-22 09:12

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('title_fa', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('title_de', models.CharField(max_length=255, null=True, verbose_name='عنوان')),
                ('desc', tinymce.models.HTMLField(verbose_name='توضیحات')),
                ('desc_fa', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('desc_en', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('desc_de', tinymce.models.HTMLField(null=True, verbose_name='توضیحات')),
                ('loc', models.CharField(max_length=155, verbose_name='موقعیت مکانی')),
                ('loc_fa', models.CharField(max_length=155, null=True, verbose_name='موقعیت مکانی')),
                ('loc_en', models.CharField(max_length=155, null=True, verbose_name='موقعیت مکانی')),
                ('loc_de', models.CharField(max_length=155, null=True, verbose_name='موقعیت مکانی')),
                ('year', models.CharField(max_length=55, verbose_name='سال')),
                ('year_fa', models.CharField(max_length=55, null=True, verbose_name='سال')),
                ('year_en', models.CharField(max_length=55, null=True, verbose_name='سال')),
                ('year_de', models.CharField(max_length=55, null=True, verbose_name='سال')),
                ('date', models.CharField(default='جمعه, 01 دی 1402 12:42:16', max_length=255, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name_plural': 'سوابق کاری',
            },
        ),
        migrations.CreateModel(
            name='Resumetitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='عنوان')),
                ('tid', models.CharField(max_length=255, verbose_name='شناسه شخصی ( id )')),
            ],
            options={
                'verbose_name_plural': 'عنوان این قسمت',
            },
        ),
    ]
