# Generated by Django 4.1.4 on 2025-06-13 22:54

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='order',
            field=models.IntegerField(blank=True, default=resume.models.count_works, null=True, verbose_name='ترتیب نمایش در لیست'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date',
            field=models.CharField(default='شنبه, 24 خرداد 1404 02:24:56', max_length=255, verbose_name='تاریخ انتشار'),
        ),
    ]
