# Generated by Django 4.1.4 on 2025-06-13 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='ترتیب نمایش در لیست'),
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.CharField(default='شنبه, 24 خرداد 1404 02:19:54', max_length=255, verbose_name='تاریخ انتشار'),
        ),
    ]
