# Generated by Django 4.1.4 on 2025-06-13 22:52

from django.db import migrations, models
import works.models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_works_order_alter_works_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.CharField(default='شنبه, 24 خرداد 1404 02:22:12', max_length=255, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='works',
            name='order',
            field=models.IntegerField(blank=True, default=works.models.count_works, null=True, verbose_name='ترتیب نمایش در لیست'),
        ),
    ]
