# Generated by Django 4.1.4 on 2025-06-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_works_date_alter_works_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='order',
        ),
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.CharField(default='شنبه, 24 خرداد 1404 02:22:48', max_length=255, verbose_name='تاریخ انتشار'),
        ),
    ]
