# Generated by Django 4.1.4 on 2025-06-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_remove_works_order_alter_works_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='date',
            field=models.CharField(default='شنبه, 24 خرداد 1404 02:24:46', max_length=255, verbose_name='تاریخ انتشار'),
        ),
    ]
